### PR TITLE
Add scripts to keep track of TOP github library registration progress

### PR DESCRIPTION
**Pull request by gandy92**

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks a lot!!! Great job!

**Comment by gandy92** [comment]
Expect more tome come - I am thinking about moving the ignore list to MarkDown format so it can be used more conveniently. I am now also adding libraries where compilation of the examples fails to the ignore list, so that I can review them at a later time.

I try resolving such issues with patches, but when a repository has many open pull-requests and appears to not have been worked on for more than a year I am not quite sure how to proceed other than putting it aside. All the repositories on the TOP list are the orinigal ones which may have been forked many times. Is there any way to find out if a repository has been abandoned by the original author, and someone else continued official active development in a fork? Especially if the original author is inactive?

**Comment by ivankravets** [comment]
Are you sure that we should generate patches for invalid libs? 

I opened here issue https://github.com/platformio/platformio/issues/108 where owners could test own libs.

**Comment by gandy92** [comment]
For me, it really depends. If the fix for the examples to compile is minor
and obvious, I include it in the pull-request (e.g. fixing upper/lower case
issues in include statements). On the other hand, if the required change is
more extensive, I tend to create an issue and wait for it to be resolved
before commencing to write the manifest file. That is when I add the
library to the ignorelist to be reviewed at a later time. That way we can
concentrate on adding quality libraries fast.

The ability for regression tests would be brilliant, it might also help
figuring out which frameworks and platforms the libraries actually work
with. Right now I simply specify arduino and atmelavr unless explicitly
noted otherwise but I might introduce too tightly set filters, there.
Am 27.03.2015 15:56 schrieb "Ivan Kravets" <notifications@github.com>:

**Comment by ivankravets** [comment]
@gandy92,

I got you, I've just opened separate issue https://github.com/platformio/platformio-api/issues/1

**Pull request merged**
